port: 8080

secret: 'taco'
expiration: 3600

database:
    dialect: 'postgres'
    host: 'localhost'
    port: 5432
    username: 'test'
    password: 'test'
    database: 'test'

session:
    name: 'nestjs-seed'
    secret: 'defaultsecret'
    resave: false
    saveUninitialized: false
    proxy: true
    cookie:
        httpOnly: true
        maxAge: 3600000
        secure: false

redis:
    host: 'localhost'

logger:
    level: debug

application:
    name: 'NestSeed'
