application:
    name: NestSeed
    port: 8080
    apiPrefix: '/api'
    bodyParserLimit: 50mb

logger:
    level: debug

authentication:
    successRoute: '/authentication/success'
    authenticationRoute: '/authentication'
    errorRoute: '/authentication?error='
    passport:
        jwt:
            strategy: 'JwtStrategy'
        google:
            strategy: 'GoogleStrategy'
            clientId: clientId
            secret: secret
            authorizedDomain: meetmaestro.com
            callbackUrl: 'http://localhost:8080/api/authentication/google/callback'
    session:
        secret: secret
        accessExpiration: 86400000 # ms - 24 hour
        accessCookie:
            name: access_token
            options:
                httpOnly: true
                maxAge: 86400000 # ms - 24 hour
                secure: true

honeyflow:
    apiKey: a6ce2f4f-fe98-4cd0-a094-46c2b5f6087b

database:
    dialect: postgres
    host: localhost
    port: 5432
    database: test

redis:
    host: localhost
    keyPrefix: 'app_'
    expiration: 86400 # sec - 24 hour


